name: TwistPy

on: [ push, pull_request ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.7.7' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install TwistPy
        shell: bash -l {0}
        run: |
          pip install .
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
